config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :cities
  resources :architects do
    member do
      post "like", to: "likes#create"
      delete "unlike", to: "likes#destroy"
    end
  end
  resources :specializations
  resources :multimedias
  resources :likes, only: [ :index]
  devise_for :users
  resources :users, only: [ :show, :edit, :update, :destroy ] do
    resources :avatars, only: [ :create, :edit, :update, :destroy ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "search", to: "search#index"
  root "home#home"

  get "legal_notice", to: "static_pages#legal_notice"
  get "rgpd", to: "static_pages#rgpd"
  get "cgv", to: "static_pages#cgv"
  get "faq", to: "static_pages#faq"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

  has_one :city, dependent: :destroy
  has_one :architect, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_one_attached :avatar
  has_many :likes, foreign_key: :client_id, dependent: :destroy
  has_many :liked_architects, through: :likes, source: :architect

  enum :role, {
    admin: 0,
    client: 1,
    architect: 2
  }

  validates :email, presence: true, uniqueness: true
  validates :role, presence: true

  # Nested attributes
  accepts_nested_attributes_for :city, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :architect, allow_destroy: true, reject_if: :all_blank

  # attribut virtuel(pas stocké sur db) pour le formulaire d'inscription
  attr_accessor :skip_city_validation

  def fullname
    if first_name.present? || last_name.present?
      "#{first_name} #{last_name}".strip
    else
      email # Fallback sur l'email si pas de nom
    end
  end

    def add_to_favorites(architect)
    likes.find_or_create_by(architect: architect)
  end

  def remove_from_favorites(architect)
    likes.find_by(architect: architect)&.destroy
  end

  def is_architect_liked?(architect)
    likes.exists?(architect: architect)
  end

  private

  # Validation  les architectes doivent avoir une ville
  # Mais seulement après l'inscription, pas lors de la création du compte
  # validates :city, presence: true, if: :should_validate_city?
  def should_validate_city?
    architect? && !skip_city_validation
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [ :create ]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name, :role ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ show edit update destroy ]


  def show
    redirect_to user_path(current_user) if params[:id].to_i != current_user.id

    @user = current_user
    if current_user.role == "architect"
      @projects = current_user.architect.projects
      @portfolio_projects = @projects.where(portfolio: true).sample(3)
      @completed_projects = @projects.where(status: :termine)
      @incoming_requests = @projects.where(status: :en_validation)
      @current_projects = @projects.where(status: :en_cours)
    else
      @projects = current_user.projects
      @completed_projects = @projects.where(status: :termine)
      @incoming_requests = @projects.where(status: :en_validation)
      @current_projects = @projects.where(status: :en_cours)

      if current_user.client?
        @favorite_architects = current_user.liked_architects.includes(:user, :specializations)
      end
    end
  end

  def edit
  end

  def update
    # Gérer les spécialisations et diplômes pour les architectes
    handle_architect_data if architect_params_present?

    if @user.update(user_params)
      redirect_to user_path(@user), notice: "Votre profil a été mis à jour avec succès."
    else
      # Ajouter les erreurs dans flash pour le débogage
      flash.now[:alert] = "Erreur lors de la mise à jour : #{@user.errors.full_messages.join(', ')}"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy!
    redirect_to root_path, notice: "Votre compte a été supprimé"
  end

  private

  def set_user
    @user = current_user
  end

  def architect_params_present?
    @user.role == "architect" && params[:user][:architect_attributes]
  end

  def handle_architect_data
    return unless @user.architect || @user.build_architect

    architect_attrs = params[:user][:architect_attributes]

    # Gérer les spécialisations - toujours traiter, même si le tableau est vide
    if architect_attrs.key?(:specialization_names)
      # Filtrer les valeurs vides du champ caché
      specialization_names = architect_attrs[:specialization_names].reject(&:blank?)
      @user.architect.specialization_names = specialization_names
    end

    # Gérer les diplômes - toujours traiter, même si le tableau est vide
    if architect_attrs.key?(:selected_degrees)
      # Filtrer les valeurs vides du champ caché
      selected_degrees = architect_attrs[:selected_degrees].reject(&:blank?)
      @user.architect.selected_degrees = selected_degrees
    end

    # Sauvegarder explicitement l'architecte
    @user.architect.save if @user.architect.changed?
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      city_attributes: [ :id, :name, :zip_code, :department ],
      architect_attributes: [ :id, :description, :degree_name, :degree_acronym, specialization_names: [], selected_degrees: [] ]
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def user_avatar_or_default
    if current_user.avatar.attached?
      image_tag current_user.avatar, alt: "avatar", class: "avatar"
    else
      image_tag "https://img.freepik.com/photos-gratuite/avatar-androgyne-personne-queer-non-binaire_23-2151100226.jpg",
                alt: "avatar par défaut",
                class: "avatar"
    end
  end


  def degree_options
    [
      [ "DEA - Diplôme d'État d'Architecte", "DEA" ],
      [ "DESA - Diplôme d'Architecte de l'École Spéciale", "DESA" ],
      [ "MA - Master en Architecture", "MA" ],
      [ "MAH - Master Architecture et Habitat", "MAH" ],
      [ "MAR - Master Architecture Résidentielle", "MAR" ],
      [ "DSAA-AI - Diplôme Supérieur d'Arts Appliqués Architecture d'Intérieur", "DSAA-AI" ],
      [ "MDEAI - Master Design d'Espace et Architecture d'Intérieur", "MDEAI" ],
      [ "BTS-DE - BTS Design d'Espace", "BTS-DE" ],
      [ "DNAT-AI - Diplôme National d'Arts et Techniques Architecture d'Intérieur", "DNAT-AI" ],
      [ "MAP - Master Architecture du Paysage", "MAP" ],
      [ "DIP - Diplôme d'Ingénieur Paysagiste", "DIP" ],
      [ "MUAP - Master Urbanisme et Aménagement Paysager", "MUAP" ],
      [ "LP-AP - Licence Professionnelle Aménagement Paysager", "LP-AP" ]
    ]
  end

  def specialization_options
    [ "Résidentielle", "Paysagère", "Intérieure" ]
  end
end

app/views/users/edit.html.erb
<% content_for :title, "Modifier mon profil" %>
<% content_for :meta_description, "Formulaire pour modifier son profil" %>

<div class="container mt-5 mb-5">
  <h1 class="mb-5 mt-100">Modifier mes informations</h1>

  <div class="card position-relative m-5 p-5">
    <!-- Affichage des erreurs -->
    <% if @user.errors.any? %>
      <div class="error-messages">
        <h4><%= pluralize(@user.errors.count, "erreur") %> :</h4>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with model: @user, url: user_path(@user), method: :patch, local: true do |f| %>
      <div class="field m-4">
        <%= f.label :first_name, "Prénom" %>
        <%= f.text_field :first_name, required: true, class:"form-control" %>
      </div>

      <div class="field m-4">
        <%= f.label :last_name, "Nom" %>
        <%= f.text_field :last_name, required: true, class:"form-control" %>
      </div>

      <!-- Informations de ville -->
      <%= f.fields_for :city, @user.city || @user.build_city do |city_fields| %>
        <div class="field m-4">
          <%= city_fields.label :department, "Département" %>
          <%= city_fields.text_field :department, id: "dept_input", class:"form-control" %>

          <%= city_fields.label :zip_code, "Code postal" %>
          <%= city_fields.text_field :zip_code, id: "zip_code_input", class:"form-control" %>

          <%= city_fields.label :name, "Ville" %>
          <%= city_fields.text_field :name, id: "city_input", class:"form-control" %>
        </div>
      <% end %>

      <!-- Informations spécifiques aux architectes -->
      <% if @user.role == "architect" %>
        <%= f.fields_for :architect, @user.architect || @user.build_architect do |architect_fields| %>
          <div class="field m-4">
            <%= architect_fields.label :description, "Description" %>
            <%= architect_fields.text_area :description, rows: 5, class:"form-control" %>
          </div>

          <div class="field m-4">
            <p><strong>Diplômes</strong></p>
            <!-- Champ caché pour forcer l'envoi d'un tableau vide si aucune checkbox n'est cochée -->
            <%= hidden_field_tag "user[architect_attributes][selected_degrees][]", "", id: "hidden_degrees" %>
            <% existing_degrees = @user.architect&.degree_acronyms_array || [] %>
            <% degree_options.each do |degree_name, degree_acronym| %>
              <div>
                <%= check_box_tag "user[architect_attributes][selected_degrees][]", degree_acronym, existing_degrees.include?(degree_acronym) %>
                <%= label_tag "user_architect_attributes_selected_degrees_#{degree_acronym}", degree_name %>
              </div>
            <% end %>
          </div>

          <div class="field m-4">
            <p><strong>Spécialités</strong></p>
            <!-- Champ caché pour forcer l'envoi d'un tableau vide si aucune checkbox n'est cochée -->
            <%= hidden_field_tag "user[architect_attributes][specialization_names][]", "", id: "hidden_specializations" %>
            <% existing_specializations = @user.architect&.specializations&.pluck(:name) || [] %>
            <% specialization_options.each do |spec| %>
              <div>
                <%= check_box_tag "user[architect_attributes][specialization_names][]", spec, existing_specializations.include?(spec) %>
                <%= label_tag "user_architect_attributes_specialization_names_#{spec}", spec %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>

        <div class="d-flex flex-column align-items-center mt-3">
        <%= f.submit "Mettre à jour", class:"btn btn-primary" %>
      </div>
    <% end %>
      </div>

    <div class="actions">
      <%= link_to "Retour", user_path(@user), class:"btn btn-primary"  %>
      <%= link_to "Modifier mon mot de passe", edit_user_registration_path, class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :title, "Dashboard" %>
<% content_for :meta_description, "Dashboard relié au profil de l'utilisateur connecté" %>

<div class="container mt-100 mb-5 px-4">
  <h1 class="mb-5"><%= current_user.fullname %></h1>

  <div class="card p-2 p-md-5 mb-5">
    <div class="d-flex flex-column flex-md-row align-items-start gap-4 w-100">

      <div class="text-center">
        <div class="avatar mb-3">
          <%= user_avatar_or_default %>
        </div>

        <!-- Bouton Modifier -->
        <div class="profil-photo-actions">
          <%= form_tag user_avatars_path(current_user), multipart: true do %>
            <label for="avatar_input" class="btn btn-warning btn-sm">Modifier l'avatar</label>
            <%= file_field_tag :avatar, id: "avatar_input", style: "display: none;" %>
          <% end %>
        </div>
      </div>
      
      <div class="container-fluid w-100 w-md-auto">
        <!-- Informations utilisateur -->
        <div>
          <h5>Informations personelles :</h5>
          <p><%= current_user.email %></p>
          <p><% if current_user.city.present? %>
            <%= current_user.city.name %> (<%= current_user.city.zip_code %>)<br>
          <% end %>
          </p>
        </div>

        <!-- Informations spécifiques aux architectes -->
        <% if current_user.role == "architect" && current_user.architect.present? %>
          <div class="architect-info">

            <% if current_user.architect.specializations.any? %>
              <div>
                <h5>spécialité :</h5>
                <ul class="list-unstyled">
                  <% current_user.architect.specializations.each do |specialization| %>
                    <li><%= specialization.name %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <% if current_user.architect.degree_names_array.any? %>
              <div class="degrees">
                <h5>Diplôme :</h5>
                <ul class="list-unstyled">
                  <% current_user.architect.degree_names_array.each do |degree| %>
                    <li class="degree-tag"><%= degree %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <% if current_user.architect.description.present? %>
              <h5>Description :</h5>
              <p><%= current_user.architect.description %></p>
            <% end %>

          </div>
        <% end %> 


        <!--modifier ou supprimer son compte-->
        <div class="d-flex gap-3 mt-4">
          <%= link_to "Modifier", edit_user_path(@user), class: "btn btn-warning btn-sm" %>
          <%= form_with url: user_registration_path, method: :delete, local: true do %>
            <%= submit_tag "Supprimer mon compte", class: "btn btn-danger btn-sm", 
                data: { confirm: "Êtes-vous sûr de vouloir supprimer votre compte ?" } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  
  <!--fonctionnalité archi-->
  <% if current_user.role == "architect" && current_user.architect.present? %>

    <h2 class="mt-5 mb-5"> Nouvelles demandes </h2>
    
      <% if @incoming_requests.present? %>
         
        <ul class="list-unstyled">
          <% @incoming_requests.each do |request|%>
            <li class="card mb-5 p-3 p-md-5">
              <h4 class="mb-4"><%= request.title%></h4>
              <p class="mb-4"><%= request.description%></p>
              <div>
                <%= link_to "Voir", project_path(request), class: "btn btn-primary" %>
              </div>
            </li>
          <%end%>
        </ul>
        
      <%else%>
        <p> Pas de nouvelle demande </p>
      <%end%>
  <%end%>
  

  <!--demande en attente de validation client-->
  <% if current_user.role == "client" %>
    <h2 class="mt-5 mb-5">Mes demandes en attente de validation</h2>
    
    <% if @incoming_requests.present? %>
      <ul class="list-unstyled">
        <% @incoming_requests.each do |project| %>
          <div class="card p-3 p-md-5 mt-4">
            <li>
              <h4><%= project.title %></h4>
              <p><%= truncate(project.description, length: 100) %></p>
              <div>
                <%= link_to "Voir", project_path(project), class: "btn btn-primary" %>
              </div>
            </li>
          </div>
        <% end %>
      </ul>
    <% else %>
      <p>Vous n'avez aucune demande en attente.</p>
    <% end %>
  <% end %>

<!-- Projet en cours pour archi et client  -->
  <h2 class="mt-100 mb-5"> Projet en cours </h2>
  <% if @current_projects.present? %>
    <ul class="list-unstyled">
      <% @current_projects.each do |project|%>
        <div class="card p-3 p-md-5 mb-4">
          <li>
            <h4><%=project.title%></h4>
            <p><%= project.description%></p>
            <div>
              <%= link_to "Voir", project_path(project), class: "btn btn-primary" %>
            </div>
          </li>
        </div>
      <%end%>
    </ul>
  <%else%>
    <p> Pas de projet en cours </p>
  <%end%>


  <h2 class="mt-100 mb-5"> Historique des projets </h2>
  <% if @completed_projects.present? %>
    <ul class="list-unstyled">
      <% @completed_projects.each do |project|%>
        <div class="card p-3 p-md-5 mt-4">
          <li>
            <h4><%=project.title%></h4>
            <p><%= project.description%></p>
            <div>
              <%= link_to "Voir", project_path(project), class: "btn btn-primary" %>
            </div>
          </li>
        </div>
      <%end%>
    </ul>
  <%else%>
    <p> Pas de projet terminé </p>
  <%end%>


  <!--fonctionnalité archi-->
  <% if current_user.role == "architect" && current_user.architect.present? %>

    <h2 class="mt-100 mb-5"> Portfolio </h2>
    <%= link_to 'Ajouter un projet au portfolio', new_project_path(user_id: current_user, architect_id: current_user.architect.id), class: "btn btn-primary" %>
    <hr>
    <% if @portfolio_projects.present? %>
      <ul class="list-unstyled">
        <% @portfolio_projects.each do |project|%>
          <div class="card p-3 p-md-5 mb-4">
            <h4><%=project.title%></h4> 
            <p><%= truncate(project.description, length: 100)%></p>
            <div>
              <%= link_to "Voir", project_path(project), class: "btn btn-primary btn-sm" %>
            </div>

            <!-- Média deja ajouté -->
            <% if project.multimedias.any? %>
              <div class="row mb-3 mt-3">
                <% project.multimedias.each do |media| %>
                  <% if media.file.attached? %>
                    <div class="col-6 col-md-4 mb-2">
                      <%= image_tag media.file, class: "img-fluid" %>
                      <% if media.description.present? %>
                        <p class="small text-muted mt-1"><%= media.description %></p>
                      <% end %>
                      <%= button_to "Supprimer", multimedia_path(media), method: :delete, data: { confirm: "Es-tu sûr de vouloir supprimer ce média ?" }, class: "btn btn-danger btn-sm mt-2" %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% else %>
              <p class="text-muted">Aucune image pour ce projet.</p>
            <% end %>
          </div>
        <%end%>
      </ul>
    <%else%>
      <p> Pas de projet dans le portfolio </p>
    <%end%>
  <%end%>

  <!--Fonctionnalité client - Favoris-->
  <% if current_user.role == "client" %>
    <h2 class="mt-100 mb-5">Mes favoris</h2>
    <% if @favorite_architects.present? %>
      <div class="row g-3">
        <% @favorite_architects.first(3).each do |architect| %>
          <div class="col-lg-4 col-md-6">
            <div class="card">
              <div class="card-body">
                <div class="d-flex align-items-center mb-3">
                  <div class="me-3">
                    <i class="fas fa-user-circle fa-2x"></i>
                  </div>
                  <div>
                    <h6 class="card-title mb-1"><%= architect.user.fullname %></h6>
                    <% if architect.user.city %>
                      <small class="text-muted"><%= architect.user.city.name %></small>
                    <% end %>
                  </div>
                </div>
                
                <% if architect.description.present? %>
                  <p class="card-text small text-muted mb-3">
                    <%= truncate(architect.description, length: 60) %>
                  </p>
                <% end %>
                
                <div class="d-flex justify-content-between align-items-center gap-2">
                  <%= link_to "Voir", architect_path(architect), 
                      class: "btn btn-primary btn-sm" %>
                  <%= render 'shared/favorites_button', architect: architect %>
                </div>
              </div>
            </div>
          </div>
          
        <% end %>
        <div class="mt-5">
          <%= link_to "Voir tous mes favoris", likes_path, class: "btn btn-primary" %>
        </div>
      </div>
    <% else %>
      <div class="text-center">
        <p class="text-muted mb-3">Vous n'avez pas encore d'architectes favoris.</p>
        <%= link_to "Découvrir des architectes", architects_path, class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>
</div>

